//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databinding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int empid { get; set; }
        public string name { get; set; }
        public string Address { get; set; }
        public Nullable<long> contact { get; set; }
        public string Gender { get; set; }
        public Nullable<int> loginID { get; set; }
    
        public virtual tblLogin tblLogin { get; set; }
    }
}
